export const interests = [
  "Machine Learning",
  "Web Development",
  "AI Research",
  "Quantum Computing",
  "Data Visualization",
  "Robotics",
  "Research",
  "Data Analysis",
  "Bioinformatics",
  "Hardware Design",
  "Pure Mathematics",
  "Cryptography",
  "Teaching",
  "Cooking",
];

export const subjects = [
  "Mathematics",
  "Science",
  "History",
  "Geography",
  "Engineering",
  "Physics",
  "Chemistry",
  "Biology",
  "Psychology",
  "Sociology",
  "Economics",
  "Political Science",
  "Linguistics",
  "Philosophy",
  "Art",
  "Music",
  "Dance",
  "Theater",
  "Film",
  "Design",
  "Architecture",
  "Journalism",
  "Journalism",
  "Business",
  "Marketing",
  "Finance",
  "Real Estate",
  "Healthcare",
  "Nursing",
  "Veterinary Medicine",
  "Pharmacy",
  "Medicine",
  "Dentistry",
  "Optometry",
];
